version: "3"
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes: # Storage can be either a
      - nginx_secrets:/etc/letsencrypt # Docker managed volume (see list at the bottom)
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d # or a host mount with a relative or full path.
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nginx_secrets:
