version: "3"
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./services/nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./services/nginx/user_conf.d:/etc/nginx/user_conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgresql:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    labels:
      NAME: "pg"
    volumes:
      - postgresql-data:/var/lib/postgresql-14/data

# Persistent Data Volumes
volumes:
  nginx_secrets:
  postgresql-data:
